name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, I am ${{ inputs.username }}!"
      
      - name: Use Secret
        run: echo "Secret is ${{ secrets.MY_SECRET }}"
